mysite/_pages/urls.py
from django.conf.urls import patterns, url
from pages.views import (
    ArticleArchiveView, ArticleDetailView, ArticleListView, PreviewView,
    PageDetailView, SearchView, ZenModeView, ZenModeUpdateView, TagListView,
    GenericTagListView)

from radpress.feeds import ArticleFeed

urlpatterns = patterns(
    '',

    url(r'^$',
        view=TagListView.as_view(),
        name='radpress-article-list'),

    url(r'^tags/$',
        view=ArticleArchiveView.as_view(),
        name='radpress-article-tags'),

    url(r'^archives/$',
        view=GenericTagListView.as_view(),
        name='radpress-article-archive'),

    url(r'^detail/(?P<slug>[-\w]+)/$',
        view=ArticleDetailView.as_view(),
        name='radpress-article-detail'),

    url(r'^p/(?P<slug>[-\w]+)/$',
        view=PageDetailView.as_view(),
        name='radpress-page-detail'),

    url(r'^preview/$',
        view=PreviewView.as_view(),
        name='radpress-preview'),

    url(r'^search/$',
        view=SearchView.as_view(),
        name='radpress-search'),

    url(r'^zen/$',
        view=ZenModeView.as_view(),
        name='radpress-zen-mode'),

    url(r'zen/(?P<pk>\d+)/$',
        view=ZenModeUpdateView.as_view(),
        name='radpress-zen-mode-update'),

    url(r'^rss/$',
        view=ArticleFeed(),
        name='radpress-rss'),

    url(r'^rss/(?P<tags>[-/\w]+)/$',
        view=ArticleFeed(),
        name='radpress-rss'),

    #url(r'^$',
        #view=ArticleListView.as_view(),
        #name='radpress-article-list'),

)

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^radpress/', include('radpress.urls'), name='radpress'),
    url(r'^support/', include('support.urls'), name='support'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),

]

mysite/radpress/urls.py
from django.conf.urls import patterns, url
from radpress.views import (
    ArticleArchiveView, ArticleDetailView, ArticleListView, PreviewView,
    PageDetailView, SearchView, ZenModeView, ZenModeUpdateView, TagListView,
    GenericTagListView, index, users, reports, alerts, museums, privacy,
    solutions, wan, carpark, contact)

from radpress.feeds import ArticleFeed

urlpatterns = patterns(
    'radpress.views',

    #url(r'^$',
    #    view=TagListView.as_view(),
    #    name='radpress-article-list'),

    url(r'^$', 'index', name='radpress_home'),

    url(r'^tags/$',
        view=ArticleArchiveView.as_view(),
        name='radpress-article-tags'),

    url(r'^archives/$',
        view=GenericTagListView.as_view(),
        name='radpress-article-archive'),

    url(r'^detail/(?P<slug>[-\w]+)/$',
        view=ArticleDetailView.as_view(),
        name='radpress-article-detail'),

    url(r'^p/(?P<slug>[-\w]+)/$',
        view=PageDetailView.as_view(),
        name='radpress-page-detail'),

    url(r'^preview/$',
        view=PreviewView.as_view(),
        name='radpress-preview'),

    url(r'^search/$',
        view=SearchView.as_view(),
        name='radpress-search'),

    url(r'^zen/$',
        view=ZenModeView.as_view(),
        name='radpress-zen-mode'),

    url(r'zen/(?P<pk>\d+)/$',
        view=ZenModeUpdateView.as_view(),
        name='radpress-zen-mode-update'),

    url(r'^rss/$',
        view=ArticleFeed(),
        name='radpress-rss'),

    url(r'^rss/(?P<tags>[-/\w]+)/$',
        view=ArticleFeed(),
        name='radpress-rss'),

    #url(r'^$',
        #view=ArticleListView.as_view(),
        #name='radpress-article-list'),

    url(r'^$',
        'index',
        name='radpress-home'),

    #url(r'^detail/features/$',
    #    view=ArticleDetailView.as_view(),
    #    name='radpress-features'),

    url(r'^about/$',
        'about',
        name='radpress-about-us'),

    url(r'^contact/$',
        'contact',
        name='radpress-contact'),

    # Features pages

    url(r'features/$',
        'features',
        name='radpress-features'),

    url(r'^features/users/$',
        'users',
        name='radpress-users'),
    
    url(r'^features/live/$',
        'live',
        name='radpress-live'),
    
    url(r'^features/reports/$',
        'reports',
        name='radpress-reports'),
    
    url(r'^features/auto/$',
        'auto',
        name='radpress-auto'),

    url(r'^features/alerts/$',
        'alerts',
        name='radpress-alerts'),

    # Solutions

    url(r'^solutions/$',
        'solutions',
        name='radpress-solutions'),

    url(r'^solutions/wan$',
        'wan',
        name='radpress-wan'),

    url(r'^solutions/cloud$',
        'cloud',
        name='radpress-cloud'),

    url(r'^solutions/smart-devices$',
        'smart',
        name='radpress-smart'),

    # Industries

    url(r'^indsutries/$',
        'industries',
        name='radpress-industries'),
    
    url(r'^industries/retail/$',
        'retail',
        name='radpress-retail'),

    url(r'^industries/museums/$',
        'museums',
        name='radpress-museum'),
    
    url(r'^industries/carparks/$',
        'carpark',
        name='radpress-carpark'),
    
    url(r'^airport/$',
        'airports',
        name='radpress-airport'),

    # Footer links

    url(r'^privacy-policy/$',
        'privacy',
        name='radpress-privacy'),

    url(r'^site-map/$',
        'sitemap',
        name='radpress-sitemap'),

    url(r'^terms-of-use/$',
        'terms',
        name='radpress-terms'),
)
    

mysite/_pages/models.py
import datetime
import os
from django.conf import settings
from django.db import models
from django.db.models import Count
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from easy_thumbnails.files import get_thumbnailer
from radpress.settings import MORE_TAG, DEFAULT_MARKUP
from radpress.readers import get_reader, get_markup_choices


class ThumbnailModelMixin(object):
    def get_thumbnail(self, path, size):
        thumbnailer = get_thumbnailer(path)
        thumb = thumbnailer.get_thumbnail({'size': size, 'crop': True})

        return thumb

    def get_thumbnail_tag(self, image, size=None):
        size = size or (50, 50)
        thumb = self.get_thumbnail(image.path, size)
        url = thumb.url.replace(
            '%s/' % settings.MEDIA_ROOT, settings.MEDIA_URL)
        res = '<a href="%s" target="_blank"><img src="%s" height="%s" /></a>'

        return res % (image.url, url, size[1])


class TagManager(models.Manager):
    def get_available_tags(self):
        """
        Receives list of available tags. To be available a tag, it should be
        used by any published article.
        """
        return self.annotate(Count('article')).filter(
            article__count__gt=0, article__is_published=True)


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    objects = TagManager()

    def __unicode__(self):
        return unicode(self.name)

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        return super(Tag, self).save(**kwargs)




class EntryImage(ThumbnailModelMixin, models.Model):
    name = models.CharField(
        max_length=100, blank=True,
        help_text=_("A simple description about image."))
    image = models.ImageField(upload_to='radpress/entry_images/')

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    def __unicode__(self):
        image_name = os.path.split(self.image.name)[1]
        return u"%s - %s" % (self.name, image_name)

    def thumbnail_tag(self):
        if not self.image:
            return ''

        return self.get_thumbnail_tag(self.image)

    thumbnail_tag.allow_tags = True
    thumbnail_tag.short_description = ''


class EntryManager(models.Manager):
    def all_published(self, **kwargs):
        return self.filter(is_published=True, **kwargs).order_by('-weight')


class Entry(models.Model):
    """
    Radpress' main model. It includes articles to show in Radpress mainpage.
    The content body is auto filled by content value after it converted to html
    from restructuredtext. And it has `is_published` to avoid viewing in blog
    list page.

    The `created_at` is set datetime information automatically when a 'new'
    blog entry saved, but `updated_at` will be updated in each save method ran.
    """
    MARKUP_CHOICES = get_markup_choices()

    title = models.CharField(max_length=500)
    markup = models.CharField(
        max_length=20, choices=MARKUP_CHOICES, default=DEFAULT_MARKUP)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    content_body = models.TextField(editable=False)
    is_published = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(
        default=datetime.datetime.now, editable=False)
    tags = models.ManyToManyField(
        Tag, blank=True)
    weight = models.IntegerField(blank=True, null=True, help_text='The total count of page hits')

    objects = EntryManager()

    def __unicode__(self):
        return unicode(self.title)

    def save(self, **kwargs):
        reader = get_reader(markup=self.markup)
        content_body, metadata = reader(self.content).read()

        if not self.content_body:
            self.content_body = content_body

        if not self.slug:
            self.slug = slugify(self.title)

        if not kwargs.pop('skip_updated_at', False):
            self.updated_at = datetime.datetime.now()

        super(Entry, self).save(**kwargs)


class Article(Entry):
    cover_image = models.ForeignKey(
        EntryImage, null=True, blank=True)


    @property
    def content_by_more(self):
        content_list = self.content_body.split(MORE_TAG, 1)
        content = content_list[0].strip()
        return content

    @models.permalink
    def get_absolute_url(self):
        return 'radpress-article-detail', [self.slug]


class ArticleTag(models.Model):
    tag = models.ForeignKey(Tag)
    article = models.ForeignKey(Article)

    def __unicode__(self):
        return u"%s - %s" % (self.tag.name, self.article)


class Page(Entry):
    @models.permalink
    def get_absolute_url(self):
        return 'radpress-page-detail', [self.slug]


class MenuManager(models.Manager):
    def get_menu_context(self):
        menus = []
        for menu in Menu.objects.filter(page__is_published=True):
            menus.append({
                'url': menu.page.get_absolute_url(),
                'title': menu.page.title
            })

        return menus


class Menu(models.Model):
    order = models.PositiveSmallIntegerField(default=3)
    page = models.ForeignKey(Page)

    objects = MenuManager()

    class Meta:
        unique_together = ('order', 'page')

    def __unicode__(self):
        return u'%s - %s' % (self.order, self.page.title)

mysite/_pages/templates/pages/partials/archive_list.html
{% load trans from i18n %}
{% load url from future %}

{% for article in object.article_set.all %}
  <div class="archive-item{% if forloop.last %} no-border{% endif %}">
    <h2 class="article-title">
      <a href="{{ article.get_absolute_url }}">{{ object.title }}</a>
    </h2>
  </div>
{% empty %}
  <p>{% trans "No entries found." %}</p>
{% endfor %}

mysite/_pages/templates/pages/partials/disqus.html
<div id="disqus_thread"></div>

<script type="text/javascript">
var disqus_shortname = '{{ RADPRESS_DISQUS }}';
(function() {
  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
  dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

mysite/_pages/templates/pages/partials/entry.html
{% comment %}
Arguments:
- summary: Default, 0
{% endcomment %}

{% load blocktrans trans from i18n %}
{% load radpress_full_name radpress_datetime from radpress_tags %}
{% load url from future %}

<div class="post">
  {% if object.cover_image %}
    <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" class="post-image">
      <img src="{{ object.cover_image.image.url }}" alt="{{ object.cover_image.name }}" />
    </a>
  {% endif %}

  <div class="title content-space">
    
    <h2><a href="{{ object.get_absolute_url }}" title="{{ object.title }}">{{ object.title }}</a></h2>
  </div>

  <div class="post-content content-space">
    {% if summary %}
      {{ object.content_by_more|safe }}
      <p><a class="more-link" href="{{ object.get_absolute_url }}">{% trans "Read more" %} →</a></p>
    {% else %}
      {{ object.content_body|safe }}
    {% endif %}
  </div>

  <div class="post-footer">

  </div>
</div>

mysite/_pages/templates/pages/partials/ga_code.html
<script>
  var _gaq=[['_setAccount','{{ RADPRESS_GA_CODE }}'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

mysite/_pages/templates/pages/partials/generic_archive_list.html
{% load trans from i18n %}
{% load url from future %}

{% for article in object.article_set.all %}
  <div class="archive-item{% if forloop.last %} no-border{% endif %}">
    <h2 class="article-title">
      <a href="{{ article.get_absolute_url }}">{{ article }}</a>
    </h2>
  </div>
{% empty %}
  <p>{% trans "No entries found." %}</p>
{% endfor %}

mysite/_pages/templates/pages/partials/navigation.html
{% load trans from i18n %}

{% if page_obj %}
  <div class="post-nav">
    {% if page_obj.has_previous %}
      <div class="postnav-left">
        <a href="?{% if enabled_tag %}tag={{ enabled_tag }}{% endif %}&page={{ page_obj.previous_page_number }}">&larr; {% trans "previous" %}</a>
      </div>
    {% endif %}

    {% if page_obj.has_next %}
      <div class="postnav-right">
        <a href="?{% if enabled_tag %}tag={{ enabled_tag }}{% endif %}&page={{ page_obj.next_page_number }}">{% trans "next" %} &rarr;</a>
      </div>
    {% endif %}
  </div>
{% endif %}

mysite/_pages/templates/pages/partials/search_form.html
{% load trans from i18n %}
{% load url from future %}

<div class="widget">
  <form class="search-form" action="{% url 'radpress-search' %}" method="GET">
    <input class="submit" type="submit" value="{% trans "Go" %}"/>
    <input type="text"
           class="search-form-input text"
           value="{% trans "Search" %}"
           onblur="if (this.value == '') {this.value = '{% trans "Search" %}';}"
           onfocus="if (this.value == '{% trans "Search" %}') {this.value = '';}"
           name="q"/>
  </form>
</div>

mysite/_pages/templates/pages/partials/share.html
{% load radpress_get_url from radpress_tags %}
{% radpress_get_url object as url %}

{% with title=object.title %}
  {# google plus #}
  <a class="share-google" href="https://plus.google.com/share?url={{ url }}" title="{{ title }}" target="blank">google</a>

  {# facebook #}
  <a class="share-facebook" href="http://www.facebook.com/share.php?u={{ url }}" title="{{ title }}" target="blank">facebook</a>

  {# twitter #}
  <a class="share-twitter" href="http://twitter.com/home?status={{ title }} - {{ url }}" title="{{ title }}" target="blank">twitter</a>
{% endwith %}

mysite/_pages/templates/pages/partials/tag_cloud.html
{% load url from future %}

<div class="widget widget-no-border">
  <div class="tagcloud">
    {% for tag in tag_list %}
      <a class="label{% if tag.slug == enabled_tag %} label-info{% endif %}"
         href="{% url 'radpress-article-archive' %}?tag={{ tag.slug }}">
        <i class="icon-tag icon-white"></i>
        {{ tag.name }}
      </a>
    {% endfor %}
  </div>
</div>

mysite/_pages/templates/pages/partials/tag_list.html
<!--{% load trans from i18n %}
{% load url from future %}

{% for article in object.article_set.all %}
    {% if article.p_tag.name != object.name %}
      <div class="archive-item{% if forloop.last %} no-border{% endif %}">
        <h2 class="article-title">
          <a href="{{ article.get_absolute_url }}">{{ article }}</a>
        </h2>
      </div>
    {% else %}
        gibberish
    {% endif %}
{% empty %}
  <p>{% trans "No entries found." %}</p>
{% endfor %}-->


{% load trans from i18n %}
{% load url from future %}

{% for article in object.articles %}
  
  <div class="archive-item{% if forloop.last %} no-border{% endif %}">
    <h2 class="article-title">
    
        <a href="{{ article.get_absolute_url }}">{{ article }}</a>
     
    </h2>
  </div>

{% empty %}
  <p>{% trans "No entries found." %}</p>
{% endfor %}